package workitout.workitout

class UserAlt {

    var WORKINFO_ID: Int = 0
    var WORKINFO_USER_ID: Int = 0
    var WORKINFO_COLUMN_MON: String = " "
    var WORKINFO_COLUMN_TUE: String = " "
    var WORKINFO_COLUMN_WED: String = " "
    var WORKINFO_COLUMN_THU: String = " "
    var WORKINFO_COLUMN_FRI: String = " "
    var WORKINFO_COLUMN_SAT: String = " "
    var WORKINFO_COLUMN_SUN: String = " "
    var WORKINFO_COLUMN_EXT: String = " "
    var WORKINFO_COLUMN_START_TIME: String = " "
    var WORKINFO_COLUMN_END_TIME: String = " "
    var WORKINFO_COLUMN_TEXT: String = " "

    constructor(WORKINFO_ID: Int, WORKINFO_USER_ID: Int, WORKINFO_COLUMN_MON: String,
                WORKINFO_COLUMN_TUE: String, WORKINFO_COLUMN_WED: String,
                WORKINFO_COLUMN_THU: String, WORKINFO_COLUMN_FRI: String,
                WORKINFO_COLUMN_SAT: String, WORKINFO_COLUMN_SUN: String,
                WORKINFO_COLUMN_EXT: String, WORKINFO_COLUMN_START_TIME: String,
                WORKINFO_COLUMN_END_TIME: String, WORKINFO_COLUMN_TEXT: String) {
        this.WORKINFO_ID = WORKINFO_ID
        this.WORKINFO_USER_ID = WORKINFO_USER_ID
        this.WORKINFO_COLUMN_MON = WORKINFO_COLUMN_MON
        this.WORKINFO_COLUMN_TUE = WORKINFO_COLUMN_TUE
        this.WORKINFO_COLUMN_WED = WORKINFO_COLUMN_WED
        this.WORKINFO_COLUMN_THU = WORKINFO_COLUMN_THU
        this.WORKINFO_COLUMN_FRI = WORKINFO_COLUMN_FRI
        this.WORKINFO_COLUMN_SAT = WORKINFO_COLUMN_SAT
        this.WORKINFO_COLUMN_SUN = WORKINFO_COLUMN_SUN
        this.WORKINFO_COLUMN_EXT = WORKINFO_COLUMN_EXT
        this.WORKINFO_COLUMN_START_TIME = WORKINFO_COLUMN_START_TIME
        this.WORKINFO_COLUMN_END_TIME = WORKINFO_COLUMN_END_TIME
        this.WORKINFO_COLUMN_TEXT = WORKINFO_COLUMN_TEXT
    }
}
